### ISSUE TITLE
Error in Emacs 26.0.50 (built from source)

### ISSUE THREAD

**Issue by therockmandolinist** [jschaf/esup#43] opened 2017-05-01 04:04 UTC
I get the following error in the latest version of emacs built from source:
```
error in process sentinel: esup-read-result: Invalid read syntax: "#"
error in process sentinel: Invalid read syntax: "#"
```
The `*esup-results*` buffer then looks odd, with a bunch of lines that start like:
```
(#s(#s(eieio--class esup-result "A record of benchmarked results."...
;;ESUP-RESULT-SEPARATOR;;   
```
Not really sure what the source of the error is or how to fix...

**Comment by jschaf** [comment] 2017-05-01 06:40
My guess would be it's an error reading byte compiled files from an earlier version.  Does emacs startup normally without esup?

**Comment by cmack** [comment] 2017-05-06 14:40
I am also seeing this error. Emacs starts up normally without esup. I tried removing and recompiling all the `elc` files in my `elpa` directory however the error persists.  Here is debugger output with `debug-on-error` toggled:

```elisp
Debugger entered--Lisp error: (invalid-read-syntax "#")
  read(#<buffer *esup-results*>)
  esup-read-result(1)
  (car (esup-read-result (point)))
  (cons (car (esup-read-result (point))) results)
  (setq results (cons (car (esup-read-result (point))) results))
  (while (setq sep-end-point (esup-next-separator-end-point)) (setq results (cons (car (esup-read-result (point))) results)) (setq esup-last-result-start-point sep-end-point) (goto-char esup-last-result-start-point))
  (if (eobp) nil (while (setq sep-end-point (esup-next-separator-end-point)) (setq results (cons (car (esup-read-result (point))) results)) (setq esup-last-result-start-point sep-end-point) (goto-char esup-last-result-start-point)))
  (save-current-buffer (set-buffer (get-buffer esup-incoming-results-buffer)) (goto-char esup-last-result-start-point) (message "at %s" esup-last-result-start-point) (if (eobp) nil (while (setq sep-end-point (esup-next-separator-end-point)) (setq results (cons (car (esup-read-result (point))) results)) (setq esup-last-result-start-point sep-end-point) (goto-char esup-last-result-start-point))))
  (let (results sep-end-point) (save-current-buffer (set-buffer (get-buffer esup-incoming-results-buffer)) (goto-char esup-last-result-start-point) (message "at %s" esup-last-result-start-point) (if (eobp) nil (while (setq sep-end-point (esup-next-separator-end-point)) (setq results (cons (car (esup-read-result ...)) results)) (setq esup-last-result-start-point sep-end-point) (goto-char esup-last-result-start-point)))) (nreverse results))
  esup-read-results()
  (esup-fontify-results (esup-read-results))
  (let* ((all-results (esup-fontify-results (esup-read-results))) (results (esup-drop-insignificant-times all-results)) (result-break (esup-propertize-string "\n" (quote result-break) t)) (inhibit-read-only t)) (save-current-buffer (set-buffer (esup-buffer)) (erase-buffer) (esup-update-percentages results) (insert (esup-render-summary results) result-break) (let* ((--cl-var-- results) (result nil)) (while (consp --cl-var--) (setq result (car --cl-var--)) (insert (render result) result-break) (setq --cl-var-- (cdr --cl-var--))) nil) (goto-char (point-min)) (pop-to-buffer (current-buffer))))
  esup-display-results()
  (cond ((string= status "finished\n") (esup-display-results)) (t (insert (format "Process %s %s" process status))))
  esup-child-process-sentinel(#<process *esup-child*> "finished\n")

```

**Comment by jschaf** [comment] 2017-05-08 22:28
Thanks for the stack trace.

Can you run esup again and then switch to the buffer `*esup-log*` and post the output?  It won't complete, but the buffer does exist.

There should be a bunch of lines like:

```
LOG: profiling sexp /Users/jschaf/.emacs.d/init.el:20 617-692 (defconst spacemacs-emacs-min-
```

**Comment by cmack** [comment] 2017-05-09 11:17
```
logged: server *esup-server*, connection *esup-server* <127.0.0.1:56118>, message accept from 127.0.0.1

name: *esup-server* <127.0.0.1:56118>, sentinel: proc: *esup-server* <127.0.0.1:56118>, event open from 127.0.0.1

logged: server *esup-server*, connection *esup-server* <127.0.0.1:56120>, message accept from 127.0.0.1

name: *esup-server* <127.0.0.1:56120>, sentinel: proc: *esup-server* <127.0.0.1:56120>, event open from 127.0.0.1

Set information from port 56118 to be the log process
LOG: loading /home/charlie/.emacs.d/init.el

Set information from port 56120 to be the results process
LOG: profiling sexp /home/charlie/.emacs.d/init.el:7 280-300 (package-initialize)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:9 302-434 (cl-defmacro cmack/with-high-g
LOG: profiling sexp /home/charlie/.emacs.d/init.el:15 458-519 (add-to-list 'load-path (expan
LOG: profiling sexp /home/charlie/.emacs.d/init.el:17 521-565 (defconst *spell-check-support
LOG: profiling sexp /home/charlie/.emacs.d/init.el:18 566-617 (defconst *windows-p* (eq syst
LOG: profiling sexp /home/charlie/.emacs.d/init.el:19 618-666 (defconst *linux-p* (eq system
LOG: profiling sexp /home/charlie/.emacs.d/init.el:20 667-710 (defconst *mac-p* (eq system-t
LOG: profiling sexp /home/charlie/.emacs.d/init.el:21 711-776 (defconst *carbon-emacs-p* (an

LOG: profiling sexp /home/charlie/.emacs.d/init.el:22 777-840 (defconst *cocoa-emacs-p* (and
LOG: profiling sexp /home/charlie/.emacs.d/init.el:25 914-1297 (add-hook 'after-init-hook
   
LOG: profiling sexp /home/charlie/.emacs.d/init.el:36 1299-1331 (setq inhibit-startup-message 
LOG: profiling sexp /home/charlie/.emacs.d/init.el:38 1333-1353 (require 'init-elpa)
LOG: loading /home/charlie/.emacs.d/init/init-elpa.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:4 196-273 (add-to-list 'package-archives

LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:5 274-350 (add-to-list 'package-archives
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:6 351-440 (add-to-list 'package-archives
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:7 441-463 (pop package-archives)
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:13 666-1025 (defun require-package (packag

LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:27 1261-1291 (require-package 'use-package)
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:28 1292-1336 (eval-when-compile
  (require 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:30 1337-1356 (require 'bind-key)

LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:31 1357-1389 (use-package diminish :ensure 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:33 1391-1508 (use-package exec-path-from-sh
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:40 1510-1573 (use-package rainbow-mode
  :e
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:44 1575-1638 (when (< emacs-major-version 2
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:47 1640-1720 (use-package rainbow-delimiter
LOG: profiling sexp /home/charlie/.emacs.d/init/init-elpa.el:104 3440-3460 (provide 'init-elpa)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:39 1354-1378 (require 'init-behavior)
LOG: loading /home/charlie/.emacs.d/init/init-behavior.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:1 1-30 (setq-default fill-column 78)

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:2 31-49 (auto-fill-mode 1)

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:3 50-72 (column-number-mode t)
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:5 74-204 (setq backup-by-copying t
    
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:11 206-329 (setq backup-directory-alist
 
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:15 331-403 (setq auto-save-file-name-tran
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:19 525-582 (add-to-list 'custom-theme-loa
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:21 584-619 (setq-default indent-tabs-mode
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:23 621-818 (use-package ediff
  :defer t

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:30 820-847 (setq indent-tabs-mode nil)

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:32 849-878 (fset 'yes-or-no-p 'y-or-n-p)

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:35 920-1224 (when window-system
  (when *l

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:44 1235-1270 (set-keyboard-coding-system 'u

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:45 1271-1306 (set-terminal-coding-system 'u
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:46 1307-1342 (prefer-coding-system       'u
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:47 1343-1378 (set-default-coding-systems 'u
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:48 1379-1426 (setq-default buffer-file-codi
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:51 1429-1545 (when (>= emacs-major-version 
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:56 1547-1566 (require 'uniquify)

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:57 1567-1629 (setq uniquify-buffer-name-sty
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:59 1631-1672 (setq custom-file "~/.emacs.d/
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:61 1674-1778 (defun tabify-buffer ()
  "TAB
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:66 1780-1890 (defun untabify-buffer ()
  "U
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:71 1892-2074 (defun cmack/prog-mode-hook ()
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:78 2076-2166 (defun cmack/after-init-hook (
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:82 2168-2219 (add-hook 'after-init-hook #'c
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:83 2220-2269 (add-hook 'prog-mode-hook #'cm

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:86 2311-2472 (dolist (hook '(eww-mode-hook 
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:90 2474-2592 (use-package aggressive-indent
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:96 2594-2670 (use-package swiper
  :ensure 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:101 2672-2750 (use-package avy
  :ensure t
 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:106 2752-2814 (use-package which-key
  :ensu
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:110 2816-2997 (use-package flyspell
  :comma
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:116 2999-3092 (use-package string-inflection
LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:120 3094-3129 (use-package which-key
  :ensu

LOG: profiling sexp /home/charlie/.emacs.d/init/init-behavior.el:123 3131-3155 (provide 'init-behavior)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:40 1379-1405 (require 'init-appearence)
LOG: loading /home/charlie/.emacs.d/init/init-appearence.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-appearence.el:1 1-424 (add-to-list 'default-frame-al

LOG: profiling sexp /home/charlie/.emacs.d/init/init-appearence.el:9 426-484 (use-package color-theme
  :if

LOG: profiling sexp /home/charlie/.emacs.d/init/init-appearence.el:12 486-613 (use-package planet-theme
  :e

LOG: profiling sexp /home/charlie/.emacs.d/init/init-appearence.el:18 615-641 (provide 'init-appearence)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:41 1406-1435 (require 'init-editing-utils)
LOG: loading /home/charlie/.emacs.d/init/init-editing-utils.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-editing-utils.el:1 1-512 (use-package multiple-cursors


LOG: profiling sexp /home/charlie/.emacs.d/init/init-editing-utils.el:14 514-543 (provide 'init-editing-utils)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:42 1436-1460 (require 'init-flycheck)
LOG: loading /home/charlie/.emacs.d/init/init-flycheck.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-flycheck.el:1 1-773 (use-package flycheck
  :ensur

LOG: profiling sexp /home/charlie/.emacs.d/init/init-flycheck.el:23 775-799 (provide 'init-flycheck)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:43 1461-1482 (require 'init-dired)
LOG: loading /home/charlie/.emacs.d/init/init-dired.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-dired.el:1 1-501 (use-package dired+
  :ensure 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-dired.el:17 503-524 (provide 'init-dired)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:44 1483-1503 (require 'init-helm)
LOG: loading /home/charlie/.emacs.d/init/init-helm.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-helm.el:1 1-190 (use-package helm-ag
  :ensure

LOG: profiling sexp /home/charlie/.emacs.d/init/init-helm.el:9 192-226 (use-package helm-config :defe

LOG: profiling sexp /home/charlie/.emacs.d/init/init-helm.el:11 228-1286 (use-package helm
  :ensure t


LOG: profiling sexp /home/charlie/.emacs.d/init/init-helm.el:41 1288-1415 (use-package helm-descbinds
  

LOG: profiling sexp /home/charlie/.emacs.d/init/init-helm.el:47 1417-1656 (use-package helm-gtags
  :ens

LOG: profiling sexp /home/charlie/.emacs.d/init/init-helm.el:58 1658-1678 (provide 'init-helm)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:45 1504-1530 (require 'init-projectile)
LOG: loading /home/charlie/.emacs.d/init/init-projectile.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-projectile.el:1 1-36 (use-package ag :ensure t :def

LOG: profiling sexp /home/charlie/.emacs.d/init/init-projectile.el:3 38-110 (use-package helm-projectile
 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-projectile.el:7 112-358 (use-package projectile
  :ens

LOG: profiling sexp /home/charlie/.emacs.d/init/init-projectile.el:17 360-386 (provide 'init-projectile)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:46 1531-1552 (require 'init-input)
LOG: loading /home/charlie/.emacs.d/init/init-input.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-input.el:1 1-38 (use-package mozc :ensure t :d

LOG: profiling sexp /home/charlie/.emacs.d/init/init-input.el:3 40-86 (use-package mozc-popup :ensur

LOG: profiling sexp /home/charlie/.emacs.d/init/init-input.el:5 88-109 (provide 'init-input)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:48 1576-1599 (require 'init-company)
LOG: loading /home/charlie/.emacs.d/init/init-company.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-company.el:1 1-110 (use-package company
  :ensure

LOG: profiling sexp /home/charlie/.emacs.d/init/init-company.el:7 112-135 (provide 'init-company)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:50 1633-1652 (require 'init-git)
LOG: loading /home/charlie/.emacs.d/init/init-git.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-git.el:1 1-167 (use-package magit
  :ensure t

LOG: profiling sexp /home/charlie/.emacs.d/init/init-git.el:9 169-188 (provide 'init-git)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:53 1699-1726 (require 'init-common-lisp)
LOG: loading /home/charlie/.emacs.d/init/init-common-lisp.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-common-lisp.el:1 1-282 (use-package paredit
  :ensure

LOG: profiling sexp /home/charlie/.emacs.d/init/init-common-lisp.el:11 284-1927 (use-package slime
  :ensure t

LOG: profiling sexp /home/charlie/.emacs.d/init/init-common-lisp.el:52 1969-3181 (defun lispdoc ()
  "Searches 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-common-lisp.el:79 3183-3210 (provide 'init-common-lisp)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:54 1727-1750 (require 'init-clojure)
LOG: loading /home/charlie/.emacs.d/init/init-clojure.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-clojure.el:1 1-120 (use-package clojure-mode
  :e

LOG: profiling sexp /home/charlie/.emacs.d/init/init-clojure.el:7 122-201 (use-package clojure-mode-extr

LOG: profiling sexp /home/charlie/.emacs.d/init/init-clojure.el:11 203-409 (use-package cider
  :ensure t
LOG: profiling sexp /home/charlie/.emacs.d/init/init-clojure.el:19 411-515 (use-package flycheck-clojure

LOG: profiling sexp /home/charlie/.emacs.d/init/init-clojure.el:25 517-592 (use-package clojurescript-mod
LOG: profiling sexp /home/charlie/.emacs.d/init/init-clojure.el:29 594-617 (provide 'init-clojure)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:55 1751-1777 (require 'init-javascript)
LOG: loading /home/charlie/.emacs.d/init/init-javascript.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-javascript.el:1 1-47 (use-package json-mode
  :defe

LOG: profiling sexp /home/charlie/.emacs.d/init/init-javascript.el:5 49-499 (use-package js2-mode
  :ensur

LOG: profiling sexp /home/charlie/.emacs.d/init/init-javascript.el:23 501-965 (use-package coffee-mode
  :en

LOG: profiling sexp /home/charlie/.emacs.d/init/init-javascript.el:41 967-993 (provide 'init-javascript)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:56 1778-1798 (require 'init-perl)
LOG: loading /home/charlie/.emacs.d/init/init-perl.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-perl.el:1 1-864 (use-package cperl-mode
  :def

LOG: profiling sexp /home/charlie/.emacs.d/init/init-perl.el:33 866-1022 (mapc
     (lambda (pair)
    

LOG: profiling sexp /home/charlie/.emacs.d/init/init-perl.el:39 1024-1044 (provide 'init-perl)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:57 1799-1821 (require 'init-python)
LOG: loading /home/charlie/.emacs.d/init/init-python.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-python.el:1 1-815 (use-package python-mode
  :co

LOG: profiling sexp /home/charlie/.emacs.d/init/init-python.el:28 819-841 (provide 'init-python)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:58 1822-1841 (require 'init-php)
LOG: loading /home/charlie/.emacs.d/init/init-php.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:1 1-136 (use-package ggtags
  :ensure 

LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:8 138-964 (use-package smartparens
  :en

LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:31 966-1023 (use-package php-extras
  :ens

LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:35 1025-1120 (use-package phpcbf
  :ensure 
LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:41 1122-1176 (use-package phpunit
  :ensure
LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:45 1178-1301 (use-package company-php
  :en

LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:51 1303-2568 (use-package php-mode
  :ensur

LOG: profiling sexp /home/charlie/.emacs.d/init/init-php.el:94 2570-2589 (provide 'init-php)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:59 1842-1862 (require 'init-ruby)
LOG: loading /home/charlie/.emacs.d/init/init-ruby.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-ruby.el:1 1-111 (use-package robe
  :ensure t


LOG: profiling sexp /home/charlie/.emacs.d/init/init-ruby.el:7 113-300 (use-package ruby-mode
  :ensu

LOG: profiling sexp /home/charlie/.emacs.d/init/init-ruby.el:17 302-322 (provide 'init-ruby)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:60 1863-1882 (require 'init-erc)
LOG: loading /home/charlie/.emacs.d/init/init-erc.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-erc.el:1 1-571 (use-package erc
  :commands e

LOG: profiling sexp /home/charlie/.emacs.d/init/init-erc.el:14 573-592 (provide 'init-erc)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:61 1883-1902 (require 'init-web)
LOG: loading /home/charlie/.emacs.d/init/init-web.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:1 1-43 (use-package haml-mode :ensure

LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:3 45-88 (use-package restclient :ensur

LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:5 90-190 (use-package scss-mode
  :ensu
LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:11 192-262 (use-package sass-mode
  :disa
LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:16 264-322 (use-package markdown-mode
  :
LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:20 324-380 (use-package yaml-mode
  :ensu
LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:24 382-534 (use-package emmet-mode
  :ens

LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:31 536-2351 (use-package web-mode
  :ensur

LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:78 2353-2597 (use-package tagedit
  :ensure

LOG: profiling sexp /home/charlie/.emacs.d/init/init-web.el:89 2599-2618 (provide 'init-web)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:63 1904-1929 (require 'init-yasnippet)
LOG: loading /home/charlie/.emacs.d/init/init-yasnippet.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-yasnippet.el:1 1-530 (use-package yasnippet
  :ensu

LOG: profiling sexp /home/charlie/.emacs.d/init/init-yasnippet.el:16 532-557 (provide 'init-yasnippet)

LOG: profiling sexp /home/charlie/.emacs.d/init.el:64 1930-1949 (require 'init-tex)
LOG: loading /home/charlie/.emacs.d/init/init-tex.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-tex.el:1 1-174 (use-package latex
  :ensure a

LOG: profiling sexp /home/charlie/.emacs.d/init/init-tex.el:10 176-726 (use-package tex
  :defer t
  

LOG: profiling sexp /home/charlie/.emacs.d/init/init-tex.el:28 728-747 (provide 'init-tex)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:65 1950-1969 (require 'init-sql)
LOG: loading /home/charlie/.emacs.d/init/init-sql.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-sql.el:1 1-60 (use-package sqlup-mode
  :ens

LOG: profiling sexp /home/charlie/.emacs.d/init/init-sql.el:5 62-226 (use-package sql-indent
  :ens

LOG: profiling sexp /home/charlie/.emacs.d/init/init-sql.el:12 228-364 (use-package sql
  :commands s

LOG: profiling sexp /home/charlie/.emacs.d/init/init-sql.el:18 366-676 (use-package sql-interactive-m
LOG: profiling sexp /home/charlie/.emacs.d/init/init-sql.el:27 678-697 (provide 'init-sql)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:66 1970-1989 (require 'init-org)
LOG: loading /home/charlie/.emacs.d/init/init-org.el

LOG: profiling sexp /home/charlie/.emacs.d/init/init-org.el:1 1-504 (use-package org
  :defer t
  

LOG: profiling sexp /home/charlie/.emacs.d/init/init-org.el:22 506-538 (use-package ox-md
  :after or

LOG: profiling sexp /home/charlie/.emacs.d/init/init-org.el:25 540-588 (use-package ox-reveal
  :ensu
LOG: profiling sexp /home/charlie/.emacs.d/init/init-org.el:29 590-609 (provide 'init-org)
LOG: profiling sexp /home/charlie/.emacs.d/init.el:68 1991-2009 (load custom-file)
LOG: loading /home/charlie/.emacs.d/custom.el

LOG: profiling sexp /home/charlie/.emacs.d/custom.el:1 1-770 (custom-set-variables
 ;; cust

LOG: profiling sexp /home/charlie/.emacs.d/custom.el:9 771-1010 (custom-set-faces
 ;; custom-s

name: *esup-server* <127.0.0.1:56120>, sentinel: proc: *esup-server* <127.0.0.1:56120>, event connection broken by remote peer

name: *esup-server* <127.0.0.1:56118>, sentinel: proc: *esup-server* <127.0.0.1:56118>, event connection broken by remote peer
```

**Comment by jschaf** [comment] 2017-05-11 05:07
Interesting.  Do you have have your dotfiles published?

The last line profiled was: LOG: profiling sexp /home/charlie/.emacs.d/custom.el:9 771-1010 (custom-set-faces

Is there any `#` in that custom-set-faces block?

**Comment by cmack** [comment] 2017-05-11 16:02
Yes my config is mostly published at https://github.com/cmack/emacs.d but I never include `custom.el` since I used for testing new customizations before committing them. I will check tonight  to see if it is doing anything odd.

**Comment by cmack** [comment] 2017-05-12 14:02
My `custom.el` did not have any `#` characters. If I make it completely blank, I still get the same error with esup

**Comment by jschaf** [comment] 2017-05-13 06:24
Oh, I have TODO comment for this.  I think esup chokes on empty files.  Should be an easy fix if that's the underlying issue.

**Comment by jschaf** [comment] 2017-05-13 08:08
I can't reproduce with emacs 25 and your dotfiles.  I *can* reproduce with emacs 26.  So it's definitely something with Emacs 26.

**Comment by jschaf** [comment] 2017-05-24 06:31
After some digging, the root cause is because Emacs 26 serializes objects differently than Emacs 25.

For this code:

```elisp
(defclass my-result ()
  ((file :initarg :file
         :initform ""
         :type string)))

(prin1-to-string (my-result "esup-result"
                            :file "joe"))
```

Emacs 25 outputs:

```elisp
"[eieio-class-tag--my-result \"joe\"]"
```

Where Emacs 26 outputs:

```emacs-lisp
"#s(#s(eieio--class my-result nil nil [#s(cl-slot-descriptor file \"\" string nil)] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (file 0)) nil ((:file . file)) [] [] #s(#1 \"\") (:custom-groups nil)) \"joe\")"
```

Then when reading the Emacs 26 output, the parser chokes on the \# sign.

I'll take a look at better serialization options for eieio.

**Comment by Townk** [comment] 2017-07-12 00:19
Any update on this one?

**Comment by velkyel** [comment] 2017-07-15 08:06
Same issue here.
GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2017-07-15

**Comment by jschaf** [comment] 2017-07-20 01:00
Sorry about the delay.  I've been away for about a month.  I'll dive back in this weekend.

**Comment by jschaf** [comment] 2017-07-26 05:01
Okay, I think this is fixed by https://github.com/jschaf/esup/commit/bc7e62dad3d830613cd9ed7401bff434b411f4fe.  I added some hand-rolled serialization since `prin1` output isn't stable across major versions.  Can you all give it a shot and let me know if it works?

**Comment by therockmandolinist** [comment] 2017-07-26 12:40
That seemed to fix this error for me. Thanks.

**Comment by jschaf** [comment] 2017-07-26 19:11
Cool, I'll mark it as closed.  If anyone else runs into this, please re-open.

**Closed by jschaf** 2017-07-26 19:11 UTC
